steps:
  - read: npm_scope
    prompt: What scope should this extension be listed under on NPM?

  - read: extension_name
    prompt: What is the name of your extension?

  - read: repo_url
    prompt: What is the URL of your repo remote?

  - update: README.md
  - update: package.json
  - update: packages/module/package.json

  - copy: packages/module/patternfly-docs/content/extensions/patternfly-extension-seed/examples/basic.md
    to: 'packages/module/patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/examples/basic.md'

  - copy: packages/module/patternfly-docs/content/extensions/patternfly-extension-seed/examples/Basic.tsx
    to: 'packages/module/patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/examples/Basic.tsx'

  - copy: packages/module/patternfly-docs/content/extensions/patternfly-extension-seed/design-guidelines/design-guidelines.md
    to: 'packages/module/patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/design-guidelines/design-guidelines.md'

  - remove: packages/module/patternfly-docs/content/extensions/patternfly-extension-seed

  - update: packages/module/patternfly-docs/generated/index.js

  - copy: packages/module/patternfly-docs/generated/extensions/patternfly-extension-seed/design-guidelines.js
    to: 'packages/module/patternfly-docs/generated/extensions/{{ extension_name | kebab-case }}/design-guidelines.js'

  - copy: packages/module/patternfly-docs/generated/extensions/patternfly-extension-seed/react.js
    to: 'packages/module/patternfly-docs/generated/extensions/{{ extension_name | kebab-case }}/react.js'

  - remove: packages/module/patternfly-docs/generated/extensions/patternfly-extension-seed

  - remove: .tmplr.yml 
