steps:
  - read: npm_scope 
    from: '@patternfly'

  - read: extension_name
    from: git.remote_name

  - read: extension_description
    from: 'This library provides patternfly extensions'

  - read: repo_url
    from: git.remote_url

  - copy: .recipes/packages/default/README.md
    to: '.'
  - update: README.md
  
  - copy: .recipes/packages/default/package.json
    to: '.'
  - update: package.json

  - copy: .recipes/packages/default/packages/module/package.json
    to: 'packages/module/package.json'
  - update: packages/module/package.json

  - copy: .recipes/packages/default/packages/module/patternfly-docs/content/extensions/patternfly-extension-seed/examples/basic.md
    to: 'packages/module/patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/examples/basic.md'

  - copy: .recipes/packages/default/packages/module/patternfly-docs/content/extensions/patternfly-extension-seed/examples/Basic.tsx
    to: 'packages/module/patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/examples/Basic.tsx'

  - copy: .recipes/packages/default/packages/module/patternfly-docs/content/extensions/patternfly-extension-seed/design-guidelines/design-guidelines.md
    to: 'packages/module/patternfly-docs/content/extensions/{{ extension_name | kebab-case }}/design-guidelines/design-guidelines.md'

  - update: packages/module/patternfly-docs/generated/index.js

  - copy: .recipes/packages/default/packages/module/patternfly-docs/generated/extensions/patternfly-extension-seed/design-guidelines.js
    to: 'packages/module/patternfly-docs/generated/extensions/{{ extension_name | kebab-case }}/design-guidelines.js'

  - copy: .recipes/packages/default/packages/module/patternfly-docs/generated/extensions/patternfly-extension-seed/react.js
    to: 'packages/module/patternfly-docs/generated/extensions/{{ extension_name | kebab-case }}/react.js'

  - copy: README-template.md
    to: README.md
  