steps:
  - read: npm_scope 
    from: env.SCOPE

  - read: extension_name
    from: git.remote_name

  - read: extension_description
    from: env.DESCRIPTION

  - read: repo_url
    from: git.remote_url


  - copy: .recipes/default/README.md
    to: 'README.md'
  - update: README.md
  
  - copy: .recipes/default/package.json
    to: 'package.json'
  - update: package.json

  - copy: .recipes/default/packages/module/package.json
    to: 'packages/module/package.json'
  - update: packages/module/package.json

  - copy: .recipes/default/packages/module/patternfly-docs/content/examples/basic.md
    to: 'packages/module/patternfly-docs/content/examples/basic.md'

  - copy: .recipes/default/packages/module/patternfly-docs/content/examples/Basic.tsx
    to: 'packages/module/patternfly-docs/content/examples/Basic.tsx'

  - copy: .recipes/default/packages/module/patternfly-docs/content/design-guidelines/design-guidelines.md
    to: 'packages/module/patternfly-docs/content/design-guidelines/design-guidelines.md'

  - copy: .recipes/default/packages/module/patternfly-docs/generated/index.js
    to: packages/module/patternfly-docs/generated/index.js
  - update: packages/module/patternfly-docs/generated/index.js

  - copy: .recipes/default/packages/module/patternfly-docs/generated/design-guidelines.js
    to: 'packages/module/patternfly-docs/generated/design-guidelines.js'

  - copy: .recipes/default/packages/module/patternfly-docs/generated/react.js
    to: 'packages/module/patternfly-docs/generated/react.js'

  